### ISSUE TITLE
Environment Templates

### ISSUE THREAD

**Issue by kburson** [tmobile/percy#19]
I need the ability to define various environment nodes that are used as templates to be inherited by other environments.  These template nodes should not be hydrated into separately deployable configuration collections.  Think of them as an abstract class, it can be inherited but cannot be instantiated.

use Case:  I want to create 2 different definitions for my qat or performance testing environments,  each template will vary by several settings.  I do not want to keep changing the values inside the nodes - rather I want to simply inherit from a template that suits my needs.  I do not want the templates to be processed by the hydration scripts as this will generate configuration collections for a non-existent environment, what's worse is if the environments define the same deployment target the templates could collide with the actual deployed environment definitions.

**Comment by standlove** [comment]
We can either make the template env name follow a specific naming convention (e.g. start with `_`), or make the hydration script take an extra argument to skip these template env name. 

which approach do you prefer?

**Comment by kburson** [comment]
I like the first one...  If I define an environment that has a name following a specified convention (defined in .percyrc) then it will be considered an abstract template that does not generate a hydrated set of config files, but that it can be inherited by another config that does.

**Comment by kburson** [comment]
from our slack conversation I see that you have already solved this as described above. thanks.
